Week2
janethuang82/taipei-day-trip-website pull request #3
Opened 2021-05-27 09:54 UTC by janethuang82

2021-05-27 14:18 UTC, cwpeng commented
請把上線的網址貼給我哦 ~

2021-05-27 15:09 UTC, janethuang82 commented
黃麗娟
http://18.116.120.206:3000/
一時太趕忘記sorry

2021-05-27 15:11 UTC, cwpeng commented
現在點進去看不到景點資訊哦 ~

2021-05-27 15:25 UTC, janethuang82 commented
現在應該可以了 剛剛app被關...sorry

2021-05-27 20:54 UTC, cwpeng requested changes
以下兩點請修正哦：
1. 第一張截圖是 1600px 寬的螢幕，我們的景點列表需要置中處理。筆電和桌機尺寸要注意 1200px ~ 1920px 寬度的螢幕。
2. 第二張截圖是 375px 寬的螢幕，整個主視覺的內容都會消失。手機尺寸要注意 360px ~ 450px 寬度的螢幕。
![18 116 120 206_3000_](https://user-images.githubusercontent.com/6104683/119895794-c490d300-bf70-11eb-8ec4-7ff0fb54c660.png)
![18 116 120 206_3000_ (1)](https://user-images.githubusercontent.com/6104683/119895803-c78bc380-bf70-11eb-86e8-71e09216f0e3.png)

2021-05-28 05:04 UTC, janethuang82 commented
老師我改好了，可以再幫我看一次嗎？謝啦～

2021-05-28 11:41 UTC, cwpeng commented
好哦，這樣就可以，請發 Review Request 給我，我才能幫你 Approve ~

2021-05-28 20:38 UTC, cwpeng approved these changes
OK.

2021-06-01 16:56 UTC, merged